server:
  port: 8103

spring:
  application:
    name: embedding
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2
      embedding:
        model: embeddinggemma

logging:
  level:
    root: info
