
### model 简单对话
GET http://127.0.0.1:8108/chat/model/chat?prompt=

### model 流式对话
GET http://127.0.0.1:8108/chat/model/stream?prompt=

### client 简单对话
GET http://127.0.0.1:8108/chat/client/chat?prompt=

### client 流式对话
GET http://127.0.0.1:8108/chat/client/stream?prompt=


