server:
  port: 8104

spring:
  application:
    name: rag-simple

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen3:8b
      embedding:
        model: bge-m3

logging:
  level:
    root: info
    org.springframework.ai: debug
    io.modelcontextprotocol: debug
    top.lrshuai.ai: info